name: EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: SSH into EC2 and Run Script
        uses: actions/checkout@v2
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Commands to SSH into the EC2 instance and run your script
            ssh -o StrictHostKeyChecking=no $username@$host "cd /home/ubuntu/github-action/test && ./test.sh"
