name: first-github-action

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  write-to-console:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Make sure you have the SSH_PRIVATE_KEY secret set in your repository

    - name: Run pwd
      run: |
        pwd
