name: Run Branch-Specific Script

on:
  push:
    branches:
      - main
      - feature1
      - feature2

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.EC2_PUBLIC_IP }}
          USER_NAME: ${{ secrets.EC2_USER }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

      - name: Run Branch-Specific Script
        run: |
          if [ "$GITHUB_REF" = "main" ]; then
            scp -i private_key -o StrictHostKeyChecking=no $HOSTNAME:/home/ubuntu/github-action/test/test.sh /tmp/test.sh
            ssh -i private_key $USER_NAME@$HOSTNAME "cd /home/ubuntu/github-action && chmod +x /tmp/test.sh && /tmp/test.sh"
          elif [ "$GITHUB_REF" = "refs/heads/feature1" ]; then
            scp -i private_key -o StrictHostKeyChecking=no your-server:/path/to/script_location2/script2.sh /tmp/script2.sh
            ssh -i private_key $USER_NAME@$HOSTNAME "cd /home/ubuntu/github-action && chmod +x /tmp/script2.sh && /tmp/script2.sh"
          elif [ "$GITHUB_REF" = "refs/heads/feature2" ]; then
            scp -i private_key -o StrictHostKeyChecking=no your-server:/path/to/script_location3/script3.sh /tmp/script3.sh
            ssh -i private_key $USER_NAME@$HOSTNAME "cd /home/ubuntu/github-action && chmod +x /tmp/script3.sh && /tmp/script3.sh"
          else
            echo "No matching script found for this branch."
          fi

